name: .NET build check

on:
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Publish
        run: dotnet build
