name: .NET

on:
  push:
    branches: ['main', 'ci']

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Build
        run: dotnet build

      - name: Publish
        run: dotnet publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          name: MediaInfoFetcher
          path: bin\Release\net8.0-windows10.0.22000.0\win-x64\publish
          retention-days: 1 day
          overwrite: true
