name: .NET Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Publish
        run: dotnet publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          name: MediaWidget
          path: bin\Release\net8.0-windows10.0.22000.0\win-x64\publish
          retention-days: 1 day
          overwrite: true
